#!/usr/bin/env python3
"""Build components/<name>/src/* into dist/<name>.js — the file Squarespace loads.

    python3 tools/build.py [component ...]      (default: every 'loader' component)

The output is a self-mounting script: it injects the CSS once, renders the HTML
into the mount element, then runs the component JS. Editing src and re-running
this updates EVERY page that embeds the component, which is the whole point —
the Squarespace blocks hold only a stub and never need touching again.

BUILDS ARE BYTE-REPRODUCIBLE ON PURPOSE. The header used to carry the build DATE,
so the same source produced different bytes on a different day, and
tools/health_check.py - which compares the served bundle against the repo build
byte for byte - reported a failure after any rebuild that changed nothing. An
alert that cries wolf gets ignored, and it is the only thing watching the live
site. Version identity comes from the content hash printed at build time.
"""
import json, os, re, sys, hashlib

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

TEMPLATE = """/* bop Aero embed: {name}
 * Built from components/{name}/src/ — DO NOT EDIT THIS FILE.
 * Edit the source and run: python3 tools/build.py {name}
 * Embedded on: {pages}
 */
(function () {{
  var NAME = {name_js};
  var STYLE_ID = 'bopaero-style-' + NAME;
  var CSS = {css};
  var HTML = {html};

  function mountPoint() {{
    var el = document.getElementById(NAME + '-mount');
    if (el) return el;
    // Fall back to the script's own parent so the stub works even if the
    // mount div is missing or was renamed in the Squarespace block.
    var s = document.currentScript || (function () {{
      var all = document.getElementsByTagName('script');
      for (var i = all.length - 1; i >= 0; i--)
        if ((all[i].src || '').indexOf(NAME + '.js') !== -1) return all[i];
      return null;
    }})();
    return s && s.parentNode;
  }}

  function boot() {{
    var m = mountPoint();
    if (!m) {{ console.warn('[bopaero:' + NAME + '] no mount point found'); return; }}
    if (m.getAttribute('data-bopaero-mounted')) return;   // never mount twice
    m.setAttribute('data-bopaero-mounted', '1');

    if (CSS && !document.getElementById(STYLE_ID)) {{
      var st = document.createElement('style');
      st.id = STYLE_ID; st.textContent = CSS;
      document.head.appendChild(st);
    }}
    m.innerHTML = HTML;

    try {{
      component(m);
    }} catch (e) {{
      console.error('[bopaero:' + NAME + '] component error', e);
    }}
  }}

  /* ── component source (verbatim from src/component.js) ─────────────── */
  function component(root) {{
{js}
  }}

  if (document.readyState === 'loading')
    document.addEventListener('DOMContentLoaded', boot);
  else boot();
}})();
"""

# NO ?v= CACHE BUSTER, DELIBERATELY. The stub is pasted into Squarespace by hand; if
# its text changed on every build, every content change would mean re-pasting every
# page - the exact problem this repo exists to remove. GitHub Pages serves the bundle
# with cache-control: max-age=600 plus an ETag, so a push propagates within ten
# minutes on its own. The pasted stub is permanent.
STUB = """<!-- bop Aero embed: {name}
     Managed in the bopaero-embeds repo — do not paste component code here.
     Edit components/{name}/src/, run tools/build.py, push. Every page updates. -->
<div id="{name}-mount"></div>
<script src="https://embeds.bopaero.com/{name}.js" defer></script>
"""

DATA_TEMPLATE = """/* bop Aero embed: {name}
 * Built from components/{name}/src/ — DO NOT EDIT THIS FILE.
 * Edit the source or a data/<id>.json, then: python3 tools/build.py {name}
 * Aircraft in this build: {ids}
 */
(function () {{
  var NAME = {name_js};
  var STYLE_ID = 'bopaero-style-' + NAME;
  var CSS = {css};
  var HTML = {html};
  var DATA = {data};

  function mount(el) {{
    if (el.getAttribute('data-bopaero-mounted')) return;
    var id = el.getAttribute('data-aircraft');
    var spec = DATA[id];
    if (!spec) {{
      console.error('[bopaero:' + NAME + '] unknown data-aircraft=' + JSON.stringify(id) +
                    '. Available: ' + Object.keys(DATA).join(', '));
      return;
    }}
    el.setAttribute('data-bopaero-mounted', '1');
    if (CSS && !document.getElementById(STYLE_ID)) {{
      var st = document.createElement('style');
      st.id = STYLE_ID; st.textContent = CSS;
      document.head.appendChild(st);
    }}
    el.innerHTML = HTML;
    var root = el.querySelector('[data-calc-root]') || el;
    try {{ {entry}(root, spec); }}
    catch (e) {{ console.error('[bopaero:' + NAME + '] ' + id + ' failed', e); }}
  }}

  var DEPS = {deps};

  function loadDeps(done) {{
    /* Squarespace blocks used to carry their own <script> tags for Leaflet etc.
       The stub cannot, so the loader pulls them itself — once per page, even if
       two components need the same library. */
    var pending = DEPS.length;
    if (!pending) return done();
    DEPS.forEach(function (d) {{
      var sel = d.type === 'css' ? 'link[href="' + d.url + '"]' : 'script[src="' + d.url + '"]';
      var existing = document.querySelector(sel);
      if (existing) {{
        if (d.type === 'css' || existing.getAttribute('data-loaded')) {{ if (!--pending) done(); return; }}
        existing.addEventListener('load', function () {{ if (!--pending) done(); }});
        return;
      }}
      var el;
      if (d.type === 'css') {{
        el = document.createElement('link'); el.rel = 'stylesheet'; el.href = d.url;
        document.head.appendChild(el); if (!--pending) done(); return;
      }}
      el = document.createElement('script'); el.src = d.url; el.async = false;
      el.addEventListener('load', function () {{ el.setAttribute('data-loaded', '1'); if (!--pending) done(); }});
      el.addEventListener('error', function () {{
        console.error('[bopaero:' + NAME + '] dependency failed to load: ' + d.url);
        if (!--pending) done();
      }});
      document.head.appendChild(el);
    }});
  }}

  function boot() {{
    var els = document.querySelectorAll('[data-embed="' + NAME + '"][data-aircraft]');
    if (!els.length) {{
      console.warn('[bopaero:' + NAME + '] no [data-embed="' + NAME + '"][data-aircraft] mount found');
      return;
    }}
    loadDeps(function () {{ Array.prototype.forEach.call(els, mount); }});
  }}

  /* ── engine (verbatim from src/component.js) ───────────────────────── */
{js}

  if (document.readyState === 'loading')
    document.addEventListener('DOMContentLoaded', boot);
  else boot();
}})();
"""

COLLECTION_TEMPLATE = """/* bop Aero embed: {name}
 * Built from components/{name}/src/ — DO NOT EDIT THIS FILE.
 * Edit the source or a data/{name}/*.json entry, then: python3 tools/build.py {name}
 * Entries in this build: {ids}
 */
(function () {{
  var NAME = {name_js};
  var STYLE_ID = 'bopaero-style-' + NAME;
  var CSS = {css};
  var HTML = {html};
  var ITEMS = {data};

  function mount(el) {{
    if (el.getAttribute('data-bopaero-mounted')) return;
    el.setAttribute('data-bopaero-mounted', '1');
    if (CSS && !document.getElementById(STYLE_ID)) {{
      var st = document.createElement('style');
      st.id = STYLE_ID; st.textContent = CSS;
      document.head.appendChild(st);
    }}
    el.innerHTML = HTML;
    /* A collection component renders MANY entries, so the mount carries filters
       rather than an id: data-limit trims the list (a teaser elsewhere on the
       site) and data-tag narrows it. Same data, several placements. */
    var opts = {{
      limit: parseInt(el.getAttribute('data-limit') || '0', 10) || 0,
      tag: el.getAttribute('data-tag') || ''
    }};
    try {{ {entry}(el, ITEMS.slice(), opts); }}
    catch (e) {{ console.error('[bopaero:' + NAME + '] failed', e); }}
  }}

  function boot() {{
    var els = document.querySelectorAll('[data-embed="' + NAME + '"]');
    if (!els.length) {{
      console.warn('[bopaero:' + NAME + '] no [data-embed="' + NAME + '"] mount found');
      return;
    }}
    Array.prototype.forEach.call(els, mount);
  }}

  /* ── engine (verbatim from src/component.js) ───────────────────────── */
{js}

  if (document.readyState === 'loading')
    document.addEventListener('DOMContentLoaded', boot);
  else boot();
}})();
"""

COLLECTION_STUB = """<!-- bop Aero embed: {name}
     Managed in the bopaero-embeds repo — do not paste content here.
     Add a post: create data/{name}/YYYY-MM-DD-slug.json, run tools/build.py, push.
     Optional attributes: data-limit="3" to show only the newest few,
     data-tag="Program" to show one category. -->
<div data-embed="{name}"></div>
<script src="https://embeds.bopaero.com/{name}.js" defer></script>
"""


DATA_STUB = """<!-- bop Aero embed: {name} ({aircraft})
     Managed in the bopaero-embeds repo — do not paste component code here.
     Edit components/{name}/src/ or data/aircraft/{aircraft}.json, run tools/build.py, push.
     Every page showing this aircraft updates. -->
<div data-embed="{name}" data-aircraft="{aircraft}"></div>
<script src="https://embeds.bopaero.com/{name}.js" defer></script>
"""


NEWS_TAGS = ('Program', 'Aircraft', 'Event', 'Press', 'Community')


def lint_news(items):
    """Fail the build on a malformed post.

    Tags are a controlled vocabulary, not free text: Raymond may export these into
    LeadConnector or QuickBooks, and "Event"/"event"/"Events" arriving as three
    categories is the kind of mess that is trivial to prevent here and tedious to
    clean up downstream. Dates are checked too because they drive the ordering -
    a typo would silently file a post in the wrong year.
    """
    import datetime
    problems = []
    for key, it in items.items():
        if not it.get('title'):
            problems.append(f'{key}: missing title')
        if not it.get('body'):
            problems.append(f'{key}: missing body')
        try:
            datetime.date.fromisoformat(str(it.get('date', '')))
        except Exception:
            problems.append(f"{key}: date {it.get('date')!r} is not YYYY-MM-DD")
        tag = it.get('tag')
        if tag and tag not in NEWS_TAGS:
            problems.append(f"{key}: tag {tag!r} is not one of {', '.join(NEWS_TAGS)}")
    if problems:
        raise SystemExit('  BUILD FAILED news:\n    ' + '\n    '.join(problems))


def lint_css_var_fallbacks(name, js):
    """Fail the build if a cssVar() lookup has no fallback.

    A token lookup that returns '' hands Leaflet an empty colour and it falls back
    to SVG defaults - black fill, no stroke - which is invisible on the navy
    background. That shipped once: tokens moved from :root to .bop-embed during the
    re-skin and every lookup silently returned ''. The map still drew its dots and
    divider, so it looked half-alive rather than broken, and no DOM check caught it
    because the paths were all present and 'visible'. A fallback makes the failure
    cosmetic instead of invisible.
    """
    bad = re.findall(r"cssVar\(\s*'(--[a-z-]+)'\s*\)", js)
    if bad:
        raise SystemExit(
            f"  BUILD FAILED {name}: cssVar() called without a fallback for "
            f"{', '.join(sorted(set(bad)))}.\n"
            f"  A missing token would render the map invisible. Pass a literal fallback."
        )


def build(name):
    cdir = os.path.join(ROOT, 'components', name)
    meta = json.load(open(os.path.join(cdir, 'component.json')))
    src = os.path.join(cdir, 'src')
    html = open(os.path.join(src, 'component.html'), encoding='utf-8').read()
    # Shared tokens lead every component's stylesheet so nothing inherits by accident.
    tokens = open(os.path.join(ROOT, 'components', '_shared', 'tokens.css'), encoding='utf-8').read()
    css  = tokens + '\n' + open(os.path.join(src, 'component.css'), encoding='utf-8').read()
    js   = open(os.path.join(src, 'component.js'),   encoding='utf-8').read()
    lint_css_var_fallbacks(name, js)

    # The collector leads every component's JS. It guards itself so it runs once
    # per page even when several embeds are present.
    telemetry = open(os.path.join(ROOT, 'components', '_shared', 'telemetry.js'),
                     encoding='utf-8').read()
    js = telemetry + '\n' + js

    body = '\n'.join('  ' + l if l.strip() else l for l in js.splitlines())

    ddir = os.path.join(ROOT, meta['dataDir']) if meta.get('dataDir') else os.path.join(cdir, 'data')
    if os.path.isdir(ddir):
        specs = {}
        for f in sorted(os.listdir(ddir)):
            if f.endswith('.json'):
                specs[f[:-5]] = json.load(open(os.path.join(ddir, f)))
        if meta.get('collection'):
            lint_news(specs)
            # Newest first, decided here so a post cannot be filed out of order by hand.
            ordered = sorted(specs.items(), key=lambda kv: str(kv[1].get('date', '')), reverse=True)
            out = COLLECTION_TEMPLATE.format(
                name=name, name_js=json.dumps(name),
                ids=', '.join(k for k, _ in ordered),
                css=json.dumps(css), html=json.dumps(html),
                data=json.dumps([dict(v, slug=k) for k, v in ordered], indent=0),
                js=body, entry=meta.get('entry', 'initComponent'))
            os.makedirs(os.path.join(ROOT, 'docs'), exist_ok=True)
            open(os.path.join(ROOT, 'docs', f'{name}.js'), 'w').write(out)
            ver = hashlib.sha256(out.encode()).hexdigest()[:8]
            os.makedirs(os.path.join(ROOT, 'snippets'), exist_ok=True)
            open(os.path.join(ROOT, 'snippets', f'{name}.html'), 'w').write(
                COLLECTION_STUB.format(name=name))
            print(f"  built docs/{name}.js  {len(out):,} bytes  v={ver}  "
                  f"entries: {len(specs)}")
            return ver

        out = DATA_TEMPLATE.format(
            name=name, name_js=json.dumps(name),
            ids=', '.join(specs), css=json.dumps(css), html=json.dumps(html),
            data=json.dumps(specs, indent=0), js=body,
            entry=meta.get('entry', 'initCalculator'),
            deps=json.dumps(meta.get('deps', [])))
        os.makedirs(os.path.join(ROOT, 'docs'), exist_ok=True)
        open(os.path.join(ROOT, 'docs', f'{name}.js'), 'w').write(out)
        ver = hashlib.sha256(out.encode()).hexdigest()[:8]
        os.makedirs(os.path.join(ROOT, 'snippets'), exist_ok=True)
        for a in specs:
            open(os.path.join(ROOT, 'snippets', f'{name}-{a}.html'), 'w').write(
                DATA_STUB.format(name=name, aircraft=a, ver=ver))
        print(f"  built docs/{name}.js  {len(out):,} bytes  v={ver}  aircraft: {', '.join(specs)}")
        return ver

    body = '\n'.join('    ' + l if l.strip() else l for l in js.splitlines())
    out = TEMPLATE.format(
        name=name, name_js=json.dumps(name),
        pages=', '.join(meta['pages']), css=json.dumps(css), html=json.dumps(html), js=body)

    os.makedirs(os.path.join(ROOT, 'docs'), exist_ok=True)
    dist = os.path.join(ROOT, 'docs', f'{name}.js')
    open(dist, 'w').write(out)

    ver = hashlib.sha256(out.encode()).hexdigest()[:8]
    os.makedirs(os.path.join(ROOT, 'snippets'), exist_ok=True)
    open(os.path.join(ROOT, 'snippets', f'{name}.html'), 'w').write(STUB.format(name=name, ver=ver))
    print(f"  built docs/{name}.js  {len(out):,} bytes  v={ver}  ({len(meta['pages'])} page(s))")
    return ver

if __name__ == '__main__':
    names = sys.argv[1:]
    if not names:
        reg = json.load(open(os.path.join(ROOT, 'registry.json')))
        names = [n for n, c in reg['components'].items() if c['mode'] == 'loader']
    for n in names: build(n)
