#!/usr/bin/env python3
"""Build components/<name>/src/* into dist/<name>.js — the file Squarespace loads.

    python3 tools/build.py [component ...]      (default: every 'loader' component)

The output is a self-mounting script: it injects the CSS once, renders the HTML
into the mount element, then runs the component JS. Editing src and re-running
this updates EVERY page that embeds the component, which is the whole point —
the Squarespace blocks hold only a stub and never need touching again.
"""
import json, os, sys, datetime, hashlib

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

TEMPLATE = """/* bop Aero embed: {name}
 * Built {stamp} from components/{name}/src/ — DO NOT EDIT THIS FILE.
 * Edit the source and run: python3 tools/build.py {name}
 * Embedded on: {pages}
 */
(function () {{
  var NAME = {name_js};
  var STYLE_ID = 'bopaero-style-' + NAME;
  var CSS = {css};
  var HTML = {html};

  function mountPoint() {{
    var el = document.getElementById(NAME + '-mount');
    if (el) return el;
    // Fall back to the script's own parent so the stub works even if the
    // mount div is missing or was renamed in the Squarespace block.
    var s = document.currentScript || (function () {{
      var all = document.getElementsByTagName('script');
      for (var i = all.length - 1; i >= 0; i--)
        if ((all[i].src || '').indexOf(NAME + '.js') !== -1) return all[i];
      return null;
    }})();
    return s && s.parentNode;
  }}

  function boot() {{
    var m = mountPoint();
    if (!m) {{ console.warn('[bopaero:' + NAME + '] no mount point found'); return; }}
    if (m.getAttribute('data-bopaero-mounted')) return;   // never mount twice
    m.setAttribute('data-bopaero-mounted', '1');

    if (CSS && !document.getElementById(STYLE_ID)) {{
      var st = document.createElement('style');
      st.id = STYLE_ID; st.textContent = CSS;
      document.head.appendChild(st);
    }}
    m.innerHTML = HTML;

    try {{
      component(m);
    }} catch (e) {{
      console.error('[bopaero:' + NAME + '] component error', e);
    }}
  }}

  /* ── component source (verbatim from src/component.js) ─────────────── */
  function component(root) {{
{js}
  }}

  if (document.readyState === 'loading')
    document.addEventListener('DOMContentLoaded', boot);
  else boot();
}})();
"""

STUB = """<!-- bop Aero embed: {name}
     Managed in the bopaero-embeds repo — do not paste component code here.
     Edit components/{name}/src/, run tools/build.py, push. Every page updates. -->
<div id="{name}-mount"></div>
<script src="https://embeds.bopaero.com/{name}.js?v={ver}" defer></script>
"""

DATA_TEMPLATE = """/* bop Aero embed: {name}
 * Built {stamp} from components/{name}/src/ — DO NOT EDIT THIS FILE.
 * Edit the source or a data/<id>.json, then: python3 tools/build.py {name}
 * Aircraft in this build: {ids}
 */
(function () {{
  var NAME = {name_js};
  var STYLE_ID = 'bopaero-style-' + NAME;
  var CSS = {css};
  var HTML = {html};
  var DATA = {data};

  function mount(el) {{
    if (el.getAttribute('data-bopaero-mounted')) return;
    var id = el.getAttribute('data-aircraft');
    var spec = DATA[id];
    if (!spec) {{
      console.error('[bopaero:' + NAME + '] unknown data-aircraft=' + JSON.stringify(id) +
                    '. Available: ' + Object.keys(DATA).join(', '));
      return;
    }}
    el.setAttribute('data-bopaero-mounted', '1');
    if (CSS && !document.getElementById(STYLE_ID)) {{
      var st = document.createElement('style');
      st.id = STYLE_ID; st.textContent = CSS;
      document.head.appendChild(st);
    }}
    el.innerHTML = HTML;
    var root = el.querySelector('[data-calc-root]');
    try {{ initCalculator(root, spec); }}
    catch (e) {{ console.error('[bopaero:' + NAME + '] ' + id + ' failed', e); }}
  }}

  function boot() {{
    var els = document.querySelectorAll('[data-aircraft]');
    if (!els.length) console.warn('[bopaero:' + NAME + '] no [data-aircraft] mount found');
    Array.prototype.forEach.call(els, mount);
  }}

  /* ── engine (verbatim from src/component.js) ───────────────────────── */
{js}

  if (document.readyState === 'loading')
    document.addEventListener('DOMContentLoaded', boot);
  else boot();
}})();
"""

DATA_STUB = """<!-- bop Aero embed: {name} ({aircraft})
     Managed in the bopaero-embeds repo — do not paste component code here.
     Edit components/{name}/src/ or data/{aircraft}.json, run tools/build.py, push.
     Every page showing this aircraft updates. -->
<div data-aircraft="{aircraft}"></div>
<script src="https://embeds.bopaero.com/{name}.js?v={ver}" defer></script>
"""


def build(name):
    cdir = os.path.join(ROOT, 'components', name)
    meta = json.load(open(os.path.join(cdir, 'component.json')))
    src = os.path.join(cdir, 'src')
    html = open(os.path.join(src, 'component.html'), encoding='utf-8').read()
    css  = open(os.path.join(src, 'component.css'),  encoding='utf-8').read()
    js   = open(os.path.join(src, 'component.js'),   encoding='utf-8').read()

    body = '\n'.join('  ' + l if l.strip() else l for l in js.splitlines())

    ddir = os.path.join(cdir, 'data')
    if os.path.isdir(ddir):
        specs = {}
        for f in sorted(os.listdir(ddir)):
            if f.endswith('.json'):
                specs[f[:-5]] = json.load(open(os.path.join(ddir, f)))
        out = DATA_TEMPLATE.format(
            name=name, name_js=json.dumps(name), stamp=datetime.date.today().isoformat(),
            ids=', '.join(specs), css=json.dumps(css), html=json.dumps(html),
            data=json.dumps(specs, indent=0), js=body)
        os.makedirs(os.path.join(ROOT, 'docs'), exist_ok=True)
        open(os.path.join(ROOT, 'docs', f'{name}.js'), 'w').write(out)
        ver = hashlib.sha256(out.encode()).hexdigest()[:8]
        os.makedirs(os.path.join(ROOT, 'snippets'), exist_ok=True)
        for a in specs:
            open(os.path.join(ROOT, 'snippets', f'{name}-{a}.html'), 'w').write(
                DATA_STUB.format(name=name, aircraft=a, ver=ver))
        print(f"  built docs/{name}.js  {len(out):,} bytes  v={ver}  aircraft: {', '.join(specs)}")
        return ver

    body = '\n'.join('    ' + l if l.strip() else l for l in js.splitlines())
    out = TEMPLATE.format(
        name=name, name_js=json.dumps(name), stamp=datetime.date.today().isoformat(),
        pages=', '.join(meta['pages']), css=json.dumps(css), html=json.dumps(html), js=body)

    os.makedirs(os.path.join(ROOT, 'docs'), exist_ok=True)
    dist = os.path.join(ROOT, 'docs', f'{name}.js')
    open(dist, 'w').write(out)

    ver = hashlib.sha256(out.encode()).hexdigest()[:8]
    os.makedirs(os.path.join(ROOT, 'snippets'), exist_ok=True)
    open(os.path.join(ROOT, 'snippets', f'{name}.html'), 'w').write(STUB.format(name=name, ver=ver))
    print(f"  built docs/{name}.js  {len(out):,} bytes  v={ver}  ({len(meta['pages'])} page(s))")
    return ver

if __name__ == '__main__':
    names = sys.argv[1:]
    if not names:
        reg = json.load(open(os.path.join(ROOT, 'registry.json')))
        names = [n for n, c in reg['components'].items() if c['mode'] == 'loader']
    for n in names: build(n)
